baseURL: https://alahmadiq8.github.io
languageCode: en-us
title: Mohammad Alahmadi's Personal Site
theme: "hugo-simple"
googleAnalytics: UA-123456789-1
enableGitInfo: true

# Generate a nice robots.txt for SEO
enableRobotsTXT: true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles: false

taxonomies:
  tag: tags

permalinks:
  post: /:title/

imaging:
  quality: 99

params:
  description: My public space where I blog about programming, and career development.
  homeMetaContent: My public space where I blog about programming, and career development.
  footer: "[Linkedin](https://www.linkedin.com/in/mohammad91/) | [GitHub](https://github.com/AlahmadiQ8) | [StackOverflow](https://stackoverflow.com/users/5431968/mmohammad) | [Twitter](https://twitter.com/MAlahmadiQ8)"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: Momonet - Mohammad Alahmadi

menu:
  main:
    - name: Home
      url: /
      weight: 10
    - name: Blog
      url: /posts/
      weight: 20
    - name: Library
      url: /library/
      weight: 20
    - name: Resume
      url: https://1drv.ms/w/s!As1_9Cfxukrb3GXFGd0GFzpn4J7b?e=pRQzY0
      weight: 30
    - name: Tags
      url: /tags/
      weight: 40
  nav:
    - name: Home
      url: /
      weight: 10
    - name: Blog
      url: /posts/
      weight: 20
    - name: Library
      url: /library/
      weight: 20
    - name: Resume
      url: https://1drv.ms/w/s!As1_9Cfxukrb3GXFGd0GFzpn4J7b?e=pRQzY0
      weight: 30
    - name: Tags
      url: /tags/
      weight: 40

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
