baseURL: https://alahmadiq8.github.io
languageCode: en-us
defaultContentLanguage: en
title: Momonet
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:title/

imaging:
  quality: 99

params:
  description: My public space where I blog about programming, and career development.
  homeMetaContent: My public space where I blog about programming, and career development.
  footer: "[Linkedin](https://www.linkedin.com/in/mohammad91/) | [GitHub](https://github.com/AlahmadiQ8) | [StackOverflow](https://stackoverflow.com/users/5431968/mmohammad) | [Twitter](https://twitter.com/MAlahmadiQ8)"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: Momonet - Mohammad Alahmadi
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Resume
      url: https://docs.google.com/document/d/1d5MUdm_CwegEFVpUBHoVmTc95fzp91RzTTRisXxMiCM/edit?usp=sharing
      weight: 2
    - name: Blog
      url: /post/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
